services:
  postgres:
    image: postgres:13
    container_name: postgres-ecommerce
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
      TZ: America/Buenos_Aires
      PGTZ: America/Buenos_Aires
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-timezone.sql:/docker-entrypoint-initdb.d/init-timezone.sql
    restart: unless-stopped
    command: >
      postgres 
      -c timezone='-03'
      -c log_timezone='-03'
      -c shared_preload_libraries=''
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ecommerce"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
